spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:nameDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    h2:
      console:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  sql:
    init:
      data-locations:
        - classpath:productos.sql
        - classpath:usuarios.sql
      mode: always

  security:
    jwt:
      filter: JwtAuthenticationFilter
      jwt: JwtAuthenticationProvider



api:
  security:
    secret=${42fc144bfdd58f320f7735a8a86fefc475885d6063566e8af1ca33c71f940542}:

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url:  jdbc:mysql://localhost:3306/midas
#    hikari:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations:
#        - classpath:productos.sql
#        - classpath:usuarios.sql
#      mode: always
#
#  security:
#    jwt:
#      filter: JwtAuthenticationFilter
#      jwt: JwtAuthenticationProvider